# Generated by Django 2.0.3 on 2018-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('numeroCasa', models.IntegerField()),
                ('complementoo', models.CharField(max_length=30)),
                ('qtd', models.IntegerField()),
            ],
        ),
    ]
